export const sampleCategories = [
  { id: 'cat_mobility', name: 'Mobility', slug: 'mobility', description: 'Wheelchairs, scooters, walkers, canes and related items.' },
  { id: 'cat_walkers', name: 'Walkers & Rollators', slug: 'walkers-rollators', description: 'Standard walkers, rollators and wheeled walkers.' },
  { id: 'cat_beds', name: 'Beds & Accessories', slug: 'beds-accessories', description: 'Hospital beds and bedside equipment.' },
  { id: 'cat_bathing', name: 'Bathing & Toileting', slug: 'bathing-toileting', description: 'Shower chairs, commodes and raised toilet seats.' },
  { id: 'cat_incontinence', name: 'Incontinence & Ostomy', slug: 'incontinence-ostomy', description: 'Incontinence supplies, ostomy and catheter products.' },
  { id: 'cat_diabetic', name: 'Diabetes & Respiratory', slug: 'diabetes-respiratory', description: 'Diabetic devices, nebulizers and respiratory supplies.' },
  { id: 'cat_braces', name: 'Braces & Footwear', slug: 'braces-footwear', description: 'Back, wrist, knee braces and therapeutic footwear.' },
  { id: 'cat_monitoring', name: 'Monitoring & Small DME', slug: 'monitoring-dme', description: 'Oximeters, blood pressure monitors, CGM readers and similar.' },
  { id: 'cat_other', name: 'Other DME', slug: 'other-dme', description: 'Miscellaneous DME supplies (excludes oxygen).'},
];

export const sampleProducts = [
  {
    id: 'prod_motorized_wheelchair',
    name: 'Motorized Wheelchair',
    slug: 'motorized-wheelchair',
    shortDescription: 'Electric motorized wheelchair for powered mobility.',
    priceCents: 250000,
    currency: 'USD',
    categoryId: 'cat_mobility',
    media: [],
    variants: [{ id: 'var_motorized_base', sku: 'MWC-BASE', name: 'Base Model', priceCents: 250000 }],
  },
  {
    id: 'prod_scooter_electric',
    name: 'Mobility Scooter',
    slug: 'mobility-scooter',
    shortDescription: '3- or 4-wheel electric scooter for personal mobility.',
    priceCents: 120000,
    currency: 'USD',
    categoryId: 'cat_mobility',
    media: [],
    variants: [{ id: 'var_scooter_std', sku: 'SCOOTER-STD', name: 'Standard', priceCents: 120000 }],
  },
  {
    id: 'prod_manual_wheelchair',
    name: 'Manual Wheelchair',
    slug: 'manual-wheelchair',
    shortDescription: 'Lightweight manual wheelchair for everyday use.',
    priceCents: 35000,
    currency: 'USD',
    categoryId: 'cat_mobility',
    media: [],
    variants: [{ id: 'var_manual_std', sku: 'MWC-STD', name: 'Standard', priceCents: 35000 }],
  },
  {
    id: 'prod_rollator',
    name: 'Rollator Walker',
    slug: 'rollator-walker',
    shortDescription: 'Three- or four-wheeled rollator with seat and storage.',
    priceCents: 8500,
    currency: 'USD',
    categoryId: 'cat_walkers',
    media: [],
    variants: [{ id: 'var_rollator_std', sku: 'ROLL-STD', name: 'Standard', priceCents: 8500 }],
  },
  {
    id: 'prod_standard_walker',
    name: 'Standard Walker',
    slug: 'standard-walker',
    shortDescription: 'Classic folding walker for stability and support.',
    priceCents: 4500,
    currency: 'USD',
    categoryId: 'cat_walkers',
    media: [],
    variants: [{ id: 'var_walker_std', sku: 'WALK-STD', name: 'Standard', priceCents: 4500 }],
  },
  {
    id: 'prod_walker_with_wheels',
    name: 'Walker with Wheels',
    slug: 'walker-with-wheels',
    shortDescription: 'Walker with front wheels for easier movement.',
    priceCents: 6500,
    currency: 'USD',
    categoryId: 'cat_walkers',
    media: [],
    variants: [{ id: 'var_walker_wheels', sku: 'WALK-WHL', name: 'With Wheels', priceCents: 6500 }],
  },
  {
    id: 'prod_hospital_bed',
    name: 'Hospital Bed',
    slug: 'hospital-bed',
    shortDescription: 'Adjustable hospital-style bed for home care.',
    priceCents: 120000,
    currency: 'USD',
    categoryId: 'cat_beds',
    media: [],
    variants: [{ id: 'var_bed_electric', sku: 'BED-ELEC', name: 'Electric Adjustable', priceCents: 120000 }],
  },
  {
    id: 'prod_incontinence_supplies',
    name: 'Incontinence Supplies Pack',
    slug: 'incontinence-supplies-pack',
    shortDescription: 'Disposable incontinence supplies (sample pack).',
    priceCents: 2500,
    currency: 'USD',
    categoryId: 'cat_incontinence',
    media: [],
    variants: [{ id: 'var_incontinence_pack', sku: 'INC-PACK', name: 'Sample Pack', priceCents: 2500 }],
  },
  {
    id: 'prod_ostomy_bag',
    name: 'Ostomy Bag',
    slug: 'ostomy-bag',
    shortDescription: 'Standard ostomy pouch for post-surgical care.',
    priceCents: 1200,
    currency: 'USD',
    categoryId: 'cat_incontinence',
    media: [],
    variants: [{ id: 'var_ostomy_single', sku: 'OST-SGL', name: 'Single', priceCents: 1200 }],
  },
  {
    id: 'prod_catheter',
    name: 'Catheter (Disposable)',
    slug: 'disposable-catheter',
    shortDescription: 'Single-use catheter supplies.',
    priceCents: 800,
    currency: 'USD',
    categoryId: 'cat_incontinence',
    media: [],
    variants: [{ id: 'var_catheter_14', sku: 'CAT-14', name: 'Size 14FR', priceCents: 800 }],
  },
  {
    id: 'prod_shower_chair',
    name: 'Shower Chair',
    slug: 'shower-chair',
    shortDescription: 'Waterproof shower chair with non-slip feet.',
    priceCents: 4500,
    currency: 'USD',
    categoryId: 'cat_bathing',
    media: [],
    variants: [{ id: 'var_shower_std', sku: 'SHWR-STD', name: 'Standard', priceCents: 4500 }],
  },
  {
    id: 'prod_bedside_commode',
    name: 'Bedside Commode',
    slug: 'bedside-commode',
    shortDescription: 'Portable bedside commode with removable bucket.',
    priceCents: 6500,
    currency: 'USD',
    categoryId: 'cat_bathing',
    media: [],
    variants: [{ id: 'var_commode_std', sku: 'COMM-STD', name: 'Standard', priceCents: 6500 }],
  },
  {
    id: 'prod_diabetic_shoes',
    name: 'Diabetic Shoes',
    slug: 'diabetic-shoes',
    shortDescription: 'Therapeutic diabetic footwear for foot protection.',
    priceCents: 9500,
    currency: 'USD',
    categoryId: 'cat_braces',
    media: [],
    variants: [{ id: 'var_diabetic_shoe', sku: 'DSH-STD', name: 'Standard', priceCents: 9500 }],
  },
  {
    id: 'prod_raised_toilet_seat',
    name: 'Raised Toilet Seat',
    slug: 'raised-toilet-seat',
    shortDescription: 'Raised seat to make toileting easier and safer.',
    priceCents: 3500,
    currency: 'USD',
    categoryId: 'cat_bathing',
    media: [],
    variants: [{ id: 'var_toilet_raised', sku: 'TOIL-RAI', name: 'Raised Seat', priceCents: 3500 }],
  },
  {
    id: 'prod_nebulizer',
    name: 'Nebulizer Machine',
    slug: 'nebulizer-machine',
    shortDescription: 'Portable nebulizer for respiratory therapy.',
    priceCents: 12000,
    currency: 'USD',
    categoryId: 'cat_diabetic',
    media: [],
    variants: [{ id: 'var_neb_standard', sku: 'NEB-STD', name: 'Standard', priceCents: 12000 }],
  },
  {
    id: 'prod_walking_cane',
    name: 'Walking Cane',
    slug: 'walking-cane',
    shortDescription: 'Adjustable walking cane with ergonomic handle.',
    priceCents: 2500,
    currency: 'USD',
    categoryId: 'cat_mobility',
    media: [],
    variants: [{ id: 'var_cane_std', sku: 'CANE-STD', name: 'Adjustable', priceCents: 2500 }],
  },
  {
    id: 'prod_bp_monitor',
    name: 'Blood Pressure Monitor',
    slug: 'blood-pressure-monitor',
    shortDescription: 'Digital upper-arm blood pressure monitor.',
    priceCents: 4500,
    currency: 'USD',
    categoryId: 'cat_monitoring',
    media: [],
    variants: [{ id: 'var_bp_std', sku: 'BPM-STD', name: 'Upper Arm', priceCents: 4500 }],
  },
  {
    id: 'prod_cgm_reader',
    name: 'CGM / Libre Reader',
    slug: 'cgm-libre-reader',
    shortDescription: 'Continuous glucose monitor (reader device).',
    priceCents: 15000,
    currency: 'USD',
    categoryId: 'cat_monitoring',
    media: [],
    variants: [{ id: 'var_cgm_std', sku: 'CGM-STD', name: 'Reader', priceCents: 15000 }],
  },
  {
    id: 'prod_back_brace',
    name: 'Back Brace',
    slug: 'back-brace',
    shortDescription: 'Supportive back brace for lumbar stabilization.',
    priceCents: 6500,
    currency: 'USD',
    categoryId: 'cat_braces',
    media: [],
    variants: [{ id: 'var_back_small', sku: 'BRACE-BK', name: 'Medium', priceCents: 6500 }],
  },
  {
    id: 'prod_wrist_brace',
    name: 'Wrist Brace',
    slug: 'wrist-brace',
    shortDescription: 'Adjustable wrist brace for support and recovery.',
    priceCents: 2200,
    currency: 'USD',
    categoryId: 'cat_braces',
    media: [],
    variants: [{ id: 'var_wrist_small', sku: 'BRACE-WR', name: 'One Size', priceCents: 2200 }],
  },
  {
    id: 'prod_knee_brace',
    name: 'Knee Brace',
    slug: 'knee-brace',
    shortDescription: 'Stabilizing knee brace for post-op and sports use.',
    priceCents: 8500,
    currency: 'USD',
    categoryId: 'cat_braces',
    media: [],
    variants: [{ id: 'var_knee_medium', sku: 'BRACE-KN', name: 'Medium', priceCents: 8500 }],
  },
  {
    id: 'prod_ankle_boot',
    name: 'Ankle Boot',
    slug: 'ankle-boot',
    shortDescription: 'Post-op ankle boot for immobilization and recovery.',
    priceCents: 5500,
    currency: 'USD',
    categoryId: 'cat_braces',
    media: [],
    variants: [{ id: 'var_ankle_small', sku: 'BOOT-ANK', name: 'Standard', priceCents: 5500 }],
  },
  {
    id: 'prod_postop_shoe',
    name: 'Post-op Shoe',
    slug: 'postop-shoe',
    shortDescription: 'Protective shoe for post-operative foot care.',
    priceCents: 4800,
    currency: 'USD',
    categoryId: 'cat_braces',
    media: [],
    variants: [{ id: 'var_postop_shoe', sku: 'PSH-STD', name: 'One Size', priceCents: 4800 }],
  },
  {
    id: 'prod_oximeter',
    name: 'Pulse Oximeter',
    slug: 'pulse-oximeter',
    shortDescription: 'Finger pulse oximeter for SpO2 and pulse monitoring.',
    priceCents: 3000,
    currency: 'USD',
    categoryId: 'cat_monitoring',
    media: [],
    variants: [{ id: 'var_oxi_std', sku: 'OXI-STD', name: 'Standard', priceCents: 3000 }],
  },
  {
    id: 'prod_other_dme',
    name: 'Other DME Supplies',
    slug: 'other-dme-supplies',
    shortDescription: 'Various durable medical equipment items (excludes oxygen).',
    priceCents: 0,
    currency: 'USD',
    categoryId: 'cat_other',
    media: [],
    variants: [{ id: 'var_other_bulk', sku: 'DME-OTHER', name: 'Assorted', priceCents: 0 }],
  },
];
